### ISSUE TITLE
能添加Hackage源否？

### ISSUE THREAD

**Issue by zaoqi** [zjulug/mirrors-web#17]
Hackage是Haskell的包。Haskell(GHC)是一个优美的充满补丁的函数式编程语言。
它太优美了，以至于我在今年从含有浙大附初的十五中的西溪中学毕业前不因为应试停止使用它。

**Comment by lingsamuel** [comment]
额其实是有的，只是主页最近两天刚好出了点小问题，而浙大最近要考试（。
http://mirrors.zju.edu.cn/hackage/
http://mirrors.zju.edu.cn/stackage/
