### ISSUE TITLE
你这镜像站多久没维护了啊？

### ISSUE THREAD

**Issue by MCredbear** [zjulug/mirrors-web#21]
我看了下deepin的镜像，最新的也就2016年

**Comment by sunoru** [comment]
![image](https://user-images.githubusercontent.com/1469360/70926479-34b8cc80-1ffb-11ea-86bc-6a79e7704ebe.png)

Deepin 的镜像是最新的

**Comment by Bill0412** [comment]
> ![image](https://user-images.githubusercontent.com/1469360/70926479-34b8cc80-1ffb-11ea-86bc-6a79e7704ebe.png)
> 
> Deepin 的镜像是最新的

Ubuntu 20怎么没有啊，现在只能被迫用清华的，呜呜
