### ISSUE TITLE
2020.02.27 发生网络错误了吗?

### ISSUE THREAD

**Issue by TonySue2000** [zjulug/mirrors-web#22]
今早起床习惯性 apt update,发现浙大镜像不可达???
然后站长之家测个速,结果不太好看啊
![image](https://user-images.githubusercontent.com/44887097/75421136-917a2100-5974-11ea-87da-e84dc7d8dbfc.png)
疫情来了,估计想修也不好修吧...
能答复一下发生了什么吗?

**Comment by sunoru** [comment]
嗯，是镜像站的硬盘满了……有去申请新的存储但是由于疫情的关系卡在申报了。

以及最近因为远程上课的事情学校机房也做了一些限制，导致外网访问也有很多问题。
